// src/config/columnConfig.js
export const McaTwoColumns = [
    'id',
    'Name',
    'Age',
    'Hostel / Day Scholar',
    'dob',
    'gender',
    'Student Contact',
    'Blood Group',
    'Bus No.',
    '10%',
    '12%',
    'CGPA in UG',
    'CGPA in PG',
    'CURRENT ARREAR',
    'Fathers Name',
    'Fathers Ph.',
    'Fathers Occupation',
    'Mothers Name',
    'Mothers Ph.',
    'Mothers Occupation',
    'Guardian Name',
    'Relationship',
    'Guardian occupation',
    'Guardian Phone No.',
    'Door No. & Street',
    'Town/ Village',
    'Post',
    'Taluk',
    'District',
    'State',
    'Pincode',
    'Country',
    'Email Id (College)',
    'Email Id (Personal)',
    'Licence Number',
    'Passport Number',
    'Aadhaar Number',
    'PAN'
];
